### PR TITLE
Lowercase support

### LINKED ISSUE #26: Lowercase support
The issue #20 was closed, lowercase support was discarded? 

it would be helpful to have this option

### PR DESCRIPTION
**Pull request by BrunoPereira-2331**

### CODE REVIEW

**Comment by ArefMozafari** [comment]
It's great @BrunoPereira-2331
Thank you

Another thing, could you please include some unit tests in Validator_test.dart?

**Review by ArefMozafari — CHANGES_REQUESTED** [review]
It's great @BrunoPereira-2331
Thank you

Another thing, could you please include some unit tests in `Validator_test.dart`?

**Comment by BrunoPereira-2331** [comment]
I created the tests for the lowercase option.

**Review by ArefMozafari — APPROVED** [review]

**Comment by ArefMozafari** [comment]
It's merged now
Thank you

**Pull request merged**
